owner: h2-invent
repo: status

sites:
  - name: H2 invent Support
    url: https://supportchat.h2-invent.com
  - name: H2 Cloud Login
    url: https://sso.h2-invent.com/resources/xtog3/login/h2_invent_4.0/img/favicon.ico
    icon: https://sso.h2-invent.com/resources/xtog3/login/h2_invent_4.0/img/favicon.ico
  - name: Jitsi Admin
    url: https://app.jitsi-admin.de/health/check
    icon: https://jitsi-admin.de/media/jits-admin-favicon.ico
  - name: Meetling-Frontend
    url: https://app.meetling.de/health/check
    icon: https://meetling.de/media/meetling-favicon.ico
  - name: Meetling-Livekit
    url: https://livekit.meetling.de/health/check
    icon: https://meetling.de/media/meetling-favicon.ico
  - name: Meetling-Backend
    url: https://livekit-rtc.meetling.de
    icon: https://meetling.de/media/meetling-favicon.ico
  - name: Unsere Schulkindbetreuung
    url: https://app.unsere-schulkindbetreuung.de
  - name: Open Datenschutzcenter Prod
    url: https://app.open-datenschutzcenter.de/health/check
  - name: Open Datenschutzcenter Demo
    url: https://demo.open-datenschutzcenter.de/health/check

status-website:
  baseUrl: /status
  name: H2 Cloud Status
  introTitle: "**H2 Cloud Status Page**"
  introMessage: News and Status related to core services in H2 Cloud
  navbar:
    - title: Status
      href: /status
    - title: GitHub
      href: https://github.com/h2-invent

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
