# Change these first
owner: h2-invent # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: H2 invent Support
    url: https://supportchat.h2-invent.com
  - name: H2 Cloud IDP
    url: https://sso.h2-invent.com/resources/xtog3/login/h2_invent_4.0/img/favicon.ico
    icon: https://sso.h2-invent.com/resources/xtog3/login/h2_invent_4.0/img/favicon.ico
  - name: Jitsi Admin
    url: https://app.jitsi-admin.de/health/check
  - name: Meetling
    url: https://app.meetling.de/health/check
    icon: https://meetling.de/media/meetling-favicon.ico
  - name: Unsere Schulkindbetreuung
    url: https://app.unsere-schulkindbetreuung.de
  - name: Open Datenschutzcenter Prod
    url: https://app.open-datenschutzcenter.de/health/check
  - name: Open Datenschutzcenter Demo
    url: https://demo.open-datenschutzcenter.de/health/check

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://h2-invent.com/wp-content/uploads/2019/04/H2-invent-2.png
  name: H2 Cloud Status
  introTitle: "**H2 Cloud Status Page**"
  introMessage: Status Page for H2 Cloud
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/h2-invent

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
